### ISSUE TITLE
Runtime.Evaluate produces a websocket error when injecting certain scripts

### ISSUE THREAD

**Issue by djmally** [mafredri/cdp#28]
Hello! I'm using this package for some Headless Chrome automation, & I'm trying to inject some utility scripts into the browser context (jquery in particular). Everything is working great, except that when I use `Runtime.Evaluate` to inject jquery into the page, I get an error saying `websocket: close 1006 (abnormal closure): unexpected EOF`.

- This doesn't happen with other scripts I've injected using the same method
- Using `Page.AddScriptToEvaluateOnLoad` appears to succeed, but `$` won't be defined in the page context even after loading a new page to trigger the evaluation
- I'm specifically trying to inject the version of jQuery that lives at `https://code.jquery.com/jquery-3.2.1.min.js`, but I've also tried v3.2.0-min, which exhibits the same bug
- I theorized that the jquery text blob I'm trying to inject is too large for the websocket, but it's only 88KB, which does not seem like it'd be a problem (moreover, WS operates over TCP, so it should chunk packets...)

**Comment by mafredri** [comment]
That's curious, even older versions of Chrome should support at least 1MB. Are you using the latest version of cdp and have you tried increasing the [write buffer size](https://godoc.org/github.com/mafredri/cdp/rpcc#WithWriteBufferSize)? Since Chrome doesn't support websocket fragmentation the write buffer size must be at least the size of the message sent over the wire (which includes json message + encoding the scripts).

cdp should do validation on the message size and give an informative error if it exceeds the buffer size, if it's not catching it in this case then that should be fixed. You wouldn't happen to be using a custom codec / net conn for rpcc?

**Comment by djmally** [comment]
I just updated to cdp v0.13.3 (was on 0.13.2 before), but the problem still persists. Increasing the RPCC write buffer size like you suggested worked (I increased it to the max of 104857586 bytes), although `$` is still undefined in my script contexts, but that's _probably_ a problem with my setup and not cdp. I am using `github.com/mafredri/cdp/rpcc` for rpcc, so nothing custom there. I'm a bit surprised I ran into this, since I'm using the latest stable version of Chrome; very strange.

**Comment by mafredri** [comment]
Thanks for the update, I’m glad increasing the buffer size worked. Not sure why $ remains undefined though, you could perhaps try assigning it to window.$ in the script. It could be that the script is being evaluated in a different scope `¯\_(ツ)_/¯`. 

> I'm a bit surprised I ran into this, since I'm using the latest stable version of Chrome; very strange.

Yeah, me too. Chrome doesn’t really handle the full web socket spec which is probably part of the reason for this, but I definitely want the user to receive more useful errors than this. This should be handled in rpcc but I’ll need to investigate some more. 

I’m currently computerless but I’ll try to look into this soon. In the meantime, if you have code that can reproduce the issue, that would be helpful.

**Comment by djmally** [comment]
Gist that reproduces the bug: https://gist.github.com/djmally/4c61df6ea70bf1634d17cbe4da934384
The demo requires a file on disk named `jquery.js` in the same directory, and a chrome instance listening on debugging port `9222`. I'm using the version of jquery located [here](https://code.jquery.com/jquery-3.2.1.min.js) locally.

Good idea with `window.$`, I'll have to see if that works. My suspicion is that `Runtime.Evaluate` and `Runtime.CallFunctionOn` get invoked in a different execution scope than expected.

**Comment by matthewmueller** [comment]
Darn, I'm running into this too. This is a self-contained script (no external deps): https://gist.github.com/matthewmueller/9320eff3056c9fadc656c553d6730975

**Comment by mafredri** [comment]
Sorry, it's taken a while to get back to this.

@matthewmueller thanks for the script. I just pushed a fix and now you should correctly see:

```console
cdp.Runtime: Evaluate: rpcc: message too large (increase write buffer size or enable compression)
```

Which is fixed by e.g.:

```go
 rpcc.Dial(..., rpcc.WithWriteBufferSize(4096*6))
```

---

@djmally did you ever solve your `window.$` issue?

**Comment by mafredri** [comment]
@djmally using your gist (chrome_test.go) jQuery seems to work just fine (after increasing write buffer size).

I tried adding this to the end (which worked fine):

```go
_, err = client.Runtime.Evaluate(context.Background(), runtime.NewEvaluateArgs(`window.$('body').append('<h1>Hello world!</h1>')`))
```

**Comment by matthewmueller** [comment]
@mafredri oh that's great thanks! I originally thought the default was at ~1MB (or whatever chrome can handle). out of curiosity, what was the reason for lowering this?

**Comment by mafredri** [comment]
The current `4096` is the default chosen by gorilla/websocket. I’ve kept this value in cdp because gorilla/websocket persistently allocates the writebuffer, meaning each connection takes up this many bytes. Raising it beyond what’s normally needed would waste memory resources.

Ideally the websocket library would not have this constraint and could dynamically allocate more, however, this problem exists because chrome does not support fragmented (split) websocket messages. Last time I reported this they bumped the limit to 100mb instead of 1mb, but raising it to 100mb is not feasible as long as we rely on gorilla/websocket.

I’m open to suggestions though on how to improve this.
